######################################################################
# Automatically generated by qmake (3.0) ?? 6? 4 13:59:44 2014
######################################################################

TEMPLATE = app
TARGET = qt_test
INCLUDEPATH += .

# Input
SOURCES += hello.cpp

QT += core gui
greaterThan(QT_MAJOR_VERSION, 4 ): QT += widgets
