######################################################################
# Automatically generated by qmake (3.0) ?? 6? 4 14:22:06 2014
######################################################################

TEMPLATE = app
TARGET = HelloWorld
INCLUDEPATH += .

# Input
SOURCES += helloworld.cpp

QT += core gui
greaterThan(QT_MAJOR_VERSION, 4 ): QT += widgets

