######################################################################
# Automatically generated by qmake (3.0) ?? 8? 25 00:58:57 2014
######################################################################

TEMPLATE = app
TARGET = HelloWorld
INCLUDEPATH += .

# Input
SOURCES += helloworld.cpp

QT += core gui widgets
